vehicle:
  tasks_per_comp_power: 20

timer:
  time_remove_rsu_assigned: 20

  
comm_range:
  v2rsu: 300            # vehicle to RSU
  v2v: 100              # vehicle to vehicle (not built yet)
  v2i: 0                # vehicle to infrastructure (not built yet)


simulation:
  ROU_FILE: 'osm_boston_common/osm.passenger.trips.xml'
  NET_FILE: 'osm_boston_common/osm.net.xml'
  FCD_FILE: 'osm_boston_common/osm_fcd.xml'
  # ROU_FILE: ''
  # NET_FILE: 'MonacoST/most.net.xml'
  # FCD_FILE: 'MonacoST/most_fcd.xml'

  num_tasks: 2000      # number of tasks
  comp_power: 5         # computation power of cars
  comp_power_std: 1     # standard deviation
  bandwidth: 5          # bandwidth of cars
  bandwidth_std: 1      # standard deviation
  num_rsu: 10           # number of RSU